In [7]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
np.random.seed(42)


In [17]:
mean = [0] * 3
cov = np.array([
    [1, 0.8, 0.7],
    [0.8, 1.5, 0.9],
    [0.7, 0.9, 2],
])

multi_variate_normal_dist = np.random.multivariate_normal(mean, cov, 100)
multi_variate_normal_dist

array([[-1.36982979, -1.49606686, -0.60926305],
       [ 2.15104351, -0.28486438, -1.75081951],
       [-0.25315134, -0.92115702, -0.63832015],
       [ 0.14338704, -1.74772192, -0.92243309],
       [ 0.34925513, -0.20324411, -0.64147732],
       [-0.35172358,  0.25925586, -1.08082952],
       [ 0.27102868, -0.19900955,  1.43307519],
       [ 0.44091228, -1.15871278, -1.31772883],
       [-0.33148846,  0.77727591, -0.42426471],
       [ 0.99284656,  0.47416161, -0.01763073],
       [-0.5959996 ,  0.81774924,  0.44956299],
       [ 0.89498456,  0.65187723, -0.18154206],
       [-0.36549765, -0.48952833, -0.6537347 ],
       [ 0.98016491,  0.91349649,  0.32857394],
       [-1.69905697, -0.01046318, -0.19655599],
       [-1.47166993, -1.07846234, -1.00892746],
       [-0.11835249, -1.31877135, -0.61550475],
       [-0.95149653,  0.24590564, -1.19813666],
       [-1.03772275, -0.96528907, -1.66943632],
       [-0.52798685, -1.28512669,  1.0282814 ],
       [-0.48580383,  0.8625931 ,  2.236

In [37]:
A = np.cov(multi_variate_normal_dist, rowvar=False)
A

array([[1.08697774, 0.72497438, 0.50527999],
       [0.72497438, 1.25096552, 0.5834363 ],
       [0.50527999, 0.5834363 , 1.4450752 ]])

In [44]:
v = np.random.rand(3,1)
v

array([[0.66168429],
       [0.48398937],
       [0.00531348]])

In [53]:
#iteration alg
max_iter = 1000
tol = pow(10, -6)
converged = False

while not converged:
    v_new = np.dot(A, v)
    print(f"cal v_new\n {v_new}")
    v_new /= np.linalg.norm(v_new)
    print(f"normalised v_new \n{v_new}")
    if np.linalg.norm(v_new-v) < tol:
        print(f"normalised v_new and v {np.linalg.norm(v_new-v)}")
        break
    v = v_new

# estimate the dominat eigen value v.T * A * v
lam = np.dot(v.T, np.dot(A,v))
print("estimated dominant eigen value", lam.item())

cal v_new
 [[1.31420628]
 [1.4841787 ]
 [1.48378736]]
normalised v_new 
[[0.53073584]
 [0.59937838]
 [0.59922034]]
normalised v_new and v 5.80864603863588e-07
estimated dominant eigen value 2.4761965731069906


In [54]:
np.linalg.eig(A)

EigResult(eigenvalues=array([2.47619657, 0.43914037, 0.86768151]), eigenvectors=array([[-0.53073571, -0.73861406, -0.41565475],
       [-0.59937825,  0.6738372 , -0.43207539],
       [-0.59922059, -0.01981657,  0.80033867]]))