In [12]:
%matplotlib inline

import numpy as np
import scipy
from numpy.polynomial import Polynomial
np.random.seed(42)

In [5]:
A = np.random.rand(4,4)
A

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451]])

In [7]:
# LU decomposition in scipy
scipy.linalg.lu(A)

(array([[0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]]),
 array([[1.        , 0.        , 0.        , 0.        ],
        [0.44992904, 1.        , 0.        , 0.        ],
        [0.72210983, 0.64868509, 1.        , 0.        ],
        [0.18742269, 0.13587524, 0.12082855, 1.        ]]),
 array([[ 0.83244264,  0.21233911,  0.18182497,  0.18340451],
        [ 0.        ,  0.85517677,  0.65018561,  0.51613947],
        [ 0.        ,  0.        , -0.53247881,  0.50265968],
        [ 0.        ,  0.        ,  0.        ,  0.70093576]]))

In [19]:
# create a small dataset for X is a single variable and Y is the target
X = np.random.randint(5, size=(5,))
B  = np.random.randint(5, size=(5,))

# Lets say we try to fit a polynomial function with degree 2 xi = [1, xi, xi**2] for each x
coeffs = [1, 1, 1]
poly_obs = Polynomial(coeffs)
poly_obs

Polynomial([1., 1., 1.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')

In [20]:
@np.vectorize(signature='()->(n)')
def create_poly_feats(x):
    return np.array([1, x, x**2])

A = create_poly_feats(X)
A
                    


array([[ 1,  3,  9],
       [ 1,  2,  4],
       [ 1,  4, 16],
       [ 1,  1,  1],
       [ 1,  3,  9]])

In [23]:
# Solving Ax = B, multiplying A.T both sides of the equation

A_T_A = np.dot(A.T, A)
A_T_B = np.dot(A.T, B)

scipy.linalg.lu(A_T_A)

(array([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.]]),
 array([[1.        , 0.        , 0.        ],
        [0.33333333, 1.        , 0.        ],
        [0.12820513, 0.98461538, 1.        ]]),
 array([[ 39.        , 127.        , 435.        ],
        [  0.        ,  -3.33333333, -18.        ],
        [  0.        ,   0.        ,   0.95384615]]))

In [ ]:
#Implement forward and backward subs to get the coefficients of X
